name: build

on:
  - push
  - pull_request

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian:oldstable
          - debian:stable
          - debian:testing
          - ubuntu:16.04
          - ubuntu:18.04
          - ubuntu:20.04
        experimental:
          - false
        include:
          - container: debian:unstable
            experimental: true
          - container: ubuntu:devel
            experimental: true
    env:
      DEBIAN_FRONTEND: nointeractive
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt --yes update
      - run: sudo apt --yes install fakeroot
      - run: >
          docker build
          --tag ${{ github.repository }}
          --build-arg 'DEBIAN_FRONTEND=noninteractive'
          --build-arg "configurations=${configurations}"
          --build-arg "image=${image}"
          --build-arg "setup=${setup}"
          .
        env:
          configurations: >-
            --enable-fail-if-missing
            --disable-smack
            --disable-selinux
            --disable-xsmp
            --disable-xsmp-interact
            --enable-luainterp=dynamic
            --enable-pythoninterp=dynamic
            --enable-python3interp=dynamic
            --enable-cscope
            --disable-netbeans
            --enable-terminal
            --enable-multibyte
            --disable-rightleft
            --disable-arabic
            --enable-gui=no
            --with-compiledby=sasa+1
            --with-features=huge
            --with-luajit
            --without-x
            --with-tlib=ncurses
          image: ${{ matrix.container }}
          setup: >-
            apt --yes update &&
            apt --yes install tzdata &&
            apt --yes install
            autoconf git make
            build-essential libncurses-dev
            gettext
            lua5.1 liblua5.1-dev luajit libluajit-5.1-dev
            python python-dev
            python3 python3-dev &&
            apt-get --yes clean &&
            rm -rf /var/lib/apt/lists/*
      - run: docker run --detach --init --rm ${{ github.repository }} tail -f /dev/null
      - run: docker cp $(docker ps -q):/tmp/vim.tar.gz .
      - run: docker cp $(docker ps -q):/root/vim-kaoriya/VERSION .
      - id: distribution
        run: >-
          echo "::set-output name=version::$(docker exec $(docker ps -q) sh -c '. /etc/os-release && echo $VERSION_CODENAME || echo sid')"
      - run: docker stop $(docker ps -q)
      - id: vim
        run: echo "::set-output name=version::$(printf -- '%b' 'all:\n\t@printf -- $(VIM_VER)' | make -f ./VERSION -f -)"
      - run: tar fvx ./vim.tar.gz
      - run: ldd ./vim/bin/vim
      - run: mkdir -p ./deb/DEBIAN ./deb/usr/local
      - run: cp -fr ./vim/* ./deb/usr/local
      - run: >-
          printf -- 'Version: %s-%s\n' "${vim_version}" "1${distribution_version}" >> ./control
        env:
          distribution_version: ${{ steps.distribution.outputs.version }}
          vim_version: ${{ steps.vim.outputs.version }}
      - run: >-
          printf -- 'Depends: %s\n' "libtinfo-dev" >> ./control
      - run: cp ./control ./deb/DEBIAN
      - run: cat ./deb/DEBIAN/control
      - run: fakeroot dpkg-deb --build deb .
      - id: deb
        run: echo "::set-output name=filename::$(ls -1 kaoriya-vim*.deb)"
      - run: dpkg -c ${deb}
        env:
          deb: ${{ steps.deb.outputs.filename }}
      - run: docker run --detach --env DEBIAN_FRONTEND=noninteractive --init --rm ${{ matrix.container }} tail -f /dev/null
      - run: docker cp ${deb} $(docker ps -q):/root
        env:
          deb: ${{ steps.deb.outputs.filename }}
      - run: docker exec $(docker ps -q) sh -c "apt --yes update && apt --yes install /root/${deb}"
        env:
          deb: ${{ steps.deb.outputs.filename }}
      - run: docker exec $(docker ps -q) sh -c 'apt --yes install locales && localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8'
      - run: docker exec $(docker ps -q) sh -c 'LANG=ja_JP.UTF-8 vim --version'
      - run: docker stop $(docker ps -q)
      - uses: actions/upload-artifact@master
        with:
          name: ${{ steps.deb.outputs.filename }}
          path: ${{ steps.deb.outputs.filename }}
